# -*- coding: utf-8 -*-
"""
RiskPilot Baseline display layer (Streamlit-free).

This module owns two things that must be testable without a Streamlit
runtime:

1. The **deterministic legacy translation** of the closed set of baseline
   sentences produced by the built-in rules (``risk_chains`` / ``impacts`` /
   ``actions``). Display-only: nothing is ever written back to project data.

2. The **per-language content selection** for the Baseline view. The single
   entry point is :func:`get_baseline_display_text`, which decides what the
   current interface language may safely display.

Hard rules enforced here:

* A project never mixes two languages in one section. When an archive for
  the current language exists, only that archive is read.
* A missing current-language archive never falls back to another language's
  *free text*. Only text that belongs to the known deterministic template
  set is translated locally; unknown text is hidden instead of being shown
  in the wrong language.
* :func:`get_baseline_display_text` is read-only: it does not mutate the
  project, does not call ``persist()``, does not touch ``st.session_state``,
  does not read ``ui_lang`` and never calls the AI. Generating a new
  language version stays an explicit, user-triggered page action.
* Risk values (``score`` / ``level`` / ``risks`` / ``selected_hazards`` and
  the S x L x E inputs) are never read or written by this module.
"""

from __future__ import annotations

from typing import Dict, List, Optional

import i18n

from utils.localized_content import (
    SOURCE_AI_GENERATED,
    legacy_ai_text_get,
    localized_content_get,
    localized_content_put,
    make_localized_record,
)

#: project key holding regenerable AI text, keyed by interface language:
#:   project["ai_text_by_language"][language]["baseline"] = payload
AI_TEXT_ARCHIVE_KEY = "ai_text_by_language"

#: Language assumed for AI text stored before the archive existed.
LEGACY_AI_TEXT_LANGUAGE = "en"

#: Separator used by the stored risk chain strings.
CHAIN_ARROW = " → "

#: Section name of the baseline payload inside the archive.
BASELINE_SECTION = "baseline"

# --- selection sources -------------------------------------------------

#: Current-language archive exists and has content.
SOURCE_LOCALIZED_ARCHIVE = "localized_archive"

#: No archive, legacy text is fully covered by the deterministic templates.
SOURCE_DETERMINISTIC_LEGACY = "deterministic_legacy"

#: No archive, legacy text is already in the current language.
SOURCE_LEGACY_CURRENT_LANGUAGE = "legacy_current_language"

#: No archive and the legacy text is in another language (partially or
#: fully unknown), so it cannot be shown as-is.
SOURCE_MISSING_CURRENT_LANGUAGE = "missing_current_language"

#: No baseline text at all.
SOURCE_EMPTY = "empty"


# ------------------------------------------------------------
# LEGACY DETERMINISTIC CONTENT (risk chains / impacts / actions)
# ------------------------------------------------------------
# Older projects (and the built-in sample projects) store these sentences in
# English. They are produced by a closed set of rules, so they are translated
# locally for display instead of being regenerated by the AI. Anything that
# is not in the tables (for example AI written free text) is returned
# unchanged by the label functions, and callers must NOT display such text in
# a different interface language.

_CHAIN_NODE_DISPLAY_KEYS = {
    "Heavy Rainfall": "chain.node.heavy_rainfall",
    "Increased Surface Runoff": "chain.node.surface_runoff",
    "Drainage Pressure": "chain.node.drainage_pressure",
    "Site Water Accumulation": "chain.node.water_accumulation",
    "Safety + Schedule + Quality Risks": "chain.node.safety_schedule_quality",
    "Safety + Schedule Risks": "chain.node.safety_schedule",
    "Safety + Schedule Risk": "chain.node.safety_schedule",
    "Safety + Quality Risks": "chain.node.safety_quality",
    "Safety Risk": "chain.node.safety",
    "Schedule Risk": "chain.node.schedule",
    "Quality Risk": "chain.node.quality",
    "Flooding": "chain.node.flooding",
    "Construction Area Inundation": "chain.node.area_inundation",
    "Equipment / Material Damage": "chain.node.equipment_damage",
    "Work Interruption": "chain.node.work_interruption",
    "Schedule Delay": "chain.node.schedule_delay",
    "Soil Saturation": "chain.node.soil_saturation",
    "Slope Instability": "chain.node.slope_instability",
    "Landslide": "chain.node.landslide",
    "Worker + Equipment Safety Risk": "chain.node.worker_equipment_safety",
    "Earthquake": "chain.node.earthquake",
    "Ground Movement": "chain.node.ground_movement",
    "Structural / Equipment Damage": "chain.node.structural_damage",
}

_IMPACT_DISPLAY_KEYS = {
    "Weather-sensitive outdoor work may be interrupted.":
        "impact.weather_sensitive_work",
    "Excavation areas may accumulate water.":
        "impact.excavation_water",
    "Excavation and slope stability may require additional monitoring.":
        "impact.excavation_slope_monitoring",
    "Structural and equipment safety may be affected by ground movement.":
        "impact.ground_movement_safety",
    "Extreme heat may increase worker fatigue and reduce productivity.":
        "impact.heat_fatigue",
    "Strong winds may affect lifting operations and temporary structures.":
        "impact.wind_lifting",
    "Construction water availability may require additional planning.":
        "impact.water_availability",
    "Emergency evacuation and fire response planning may be required.":
        "impact.emergency_planning",
    "No major environmental construction impact has been identified from "
    "the selected conditions.":
        "impact.none_selected",
    "No major environmental construction impact has been identified.":
        "impact.none_selected",
    "No major environmental construction impact identified.":
        "impact.none",
    "AI environmental assessment was unavailable.":
        "impact.ai_unavailable",
}

_ACTION_DISPLAY_KEYS = {
    "Monitor weather conditions and prepare temporary rain protection.":
        "action.monitor_weather_protection",
    "Inspect drainage systems and prepare emergency pumping equipment.":
        "action.inspect_drainage_pump",
    "Add identified environmental risks to the project risk register.":
        "action.add_to_register",
    "Inspect slopes and excavation edges after heavy rainfall.":
        "action.inspect_slopes_after_rain",
    "Review seismic emergency procedures and structural requirements.":
        "action.review_seismic",
    "Plan appropriate rest periods and monitor worker heat exposure.":
        "action.heat_rest",
    "Establish wind-related suspension criteria for lifting operations.":
        "action.wind_suspension",
    "Review construction water availability and emergency supply plans.":
        "action.water_plan",
    "Review emergency evacuation and fire response procedures.":
        "action.review_evacuation",
    "Verify environmental conditions manually before construction begins.":
        "action.verify_manually",
    "Continue routine environmental monitoring.":
        "action.continue_monitoring",
    "Monitor weather conditions.":
        "action.monitor_weather",
    "Inspect drainage systems regularly.":
        "action.inspect_drainage",
    "Inspect drainage systems.":
        "action.inspect_drainage",
    "Monitor slope stability.":
        "action.monitor_slope",
}


# ------------------------------------------------------------
# DISPLAY-ONLY LABELS
# ------------------------------------------------------------

def _translate(key: str, language=None) -> str:
    """
    Translate a key for an explicit language, or for the current UI
    language when ``language`` is omitted.
    """
    if language is None:
        return i18n.t(key)

    return i18n.load_locale(language).get(key, key)


def _mapped(value, mapping, language=None) -> str:
    """
    Display-only localization of one internal value through a mapping.

    Values that are not in the mapping are returned unchanged (never
    pretended to be translated).
    """
    raw = "" if value is None else str(value).strip()

    if not raw:
        return raw

    key = mapping.get(raw)

    if key:
        text = _translate(key, language)
        if text != key:
            return text

    return raw


def chain_node_label(node, language=None) -> str:
    """Display-only label for one risk chain node."""
    return _mapped(node, _CHAIN_NODE_DISPLAY_KEYS, language)


def risk_chain_label(chain, language=None) -> str:
    """
    Display-only localization of a stored risk chain (``A → B → C``).

    The chain is translated node by node so that a chain with reordered or
    partially known nodes still renders as far as possible. Unknown nodes are
    kept as they are.
    """
    text = "" if chain is None else str(chain).strip()

    if not text:
        return text

    nodes = [part.strip() for part in text.split(CHAIN_ARROW)]

    if len(nodes) < 2:
        return chain_node_label(text, language)

    return CHAIN_ARROW.join(
        chain_node_label(node, language) for node in nodes
    )


def impact_label(text, language=None) -> str:
    """Display-only localization of a stored deterministic impact."""
    return _mapped(text, _IMPACT_DISPLAY_KEYS, language)


def action_label(text, language=None) -> str:
    """Display-only localization of a stored deterministic action."""
    return _mapped(text, _ACTION_DISPLAY_KEYS, language)


# ------------------------------------------------------------
# "IS THIS KNOWN DETERMINISTIC TEMPLATE TEXT?" PREDICATES
# ------------------------------------------------------------

def _known_keys_for_chain(chain) -> List[str]:
    text = "" if chain is None else str(chain).strip()

    if not text:
        return []

    nodes = [part.strip() for part in text.split(CHAIN_ARROW)]

    if len(nodes) < 2:
        return [text]

    return [node for node in nodes if node]


def is_chain_known(chain) -> bool:
    """
    True when every node of the chain belongs to the deterministic table,
    i.e. the chain can be translated locally and safely.
    """
    keys = _known_keys_for_chain(chain)

    if not keys:
        return False

    return all(key in _CHAIN_NODE_DISPLAY_KEYS for key in keys)


def is_impact_known(text) -> bool:
    """True when the impact belongs to the deterministic table."""
    return str(text).strip() in _IMPACT_DISPLAY_KEYS


def is_action_known(text) -> bool:
    """True when the action belongs to the deterministic table."""
    return str(text).strip() in _ACTION_DISPLAY_KEYS


# ------------------------------------------------------------
# AI TEXT ARCHIVE (pure readers / writers)
# ------------------------------------------------------------
# The Streamlit-facing wrappers in app.py pass the current UI language; the
# functions below stay pure so they can be tested with plain dicts.

def estimated_text_language(container) -> str:
    """Language of AI text stored before the per-language archive existed."""
    if isinstance(container, dict):
        stored = container.get("language")

        if stored in i18n.SUPPORTED_LANGUAGES:
            return stored

    return LEGACY_AI_TEXT_LANGUAGE


def ai_text_lookup(project, section, record_id=None, language=None):
    """
    Return the AI text stored for one language, or None when missing.

    Stage 3 read order (**first hit wins**):

    1. the unified protocol ``project["localized_content"]`` — exact
       ``content_type`` + ``record_id`` + ``locale`` match
       (``"log"`` / ``"logs"`` and the other legacy section spellings are
       normalised to the same content_type first);
    2. the legacy ``project["ai_text_by_language"]`` archive.

    Both probes are read-only and language-exact: a version stored in another
    language is never returned as a fallback. A new record always wins over an
    older archive entry for the same language.
    """
    if not isinstance(project, dict):
        return None

    resolved = language or i18n.DEFAULT_LANGUAGE

    # --- 1. unified localized content protocol (new records win) -----
    record = localized_content_get(project, section, resolved, record_id)

    if isinstance(record, dict):
        payload = record.get("payload")

        if isinstance(payload, dict) and payload:
            return payload

    # --- 2. legacy per-language archive ------------------------------
    return legacy_ai_text_get(project, section, resolved, record_id)


def ai_text_store(
    project,
    section,
    payload,
    record_id=None,
    language=None,
) -> None:
    """
    Store regenerable AI text under one language.

    Stage 3 writes the **unified protocol record** (``localized_content``,
    ``source="ai_generated"``) and keeps the legacy ``ai_text_by_language``
    archive in sync, so everything that still reads the old structure keeps
    working unchanged. Writing one language never removes another one, so
    regenerating the Chinese version can never overwrite the English version
    (and vice versa).

    The write is in place because the Streamlit layer persists ``project``
    afterwards; this helper never persists, never calls the AI and never
    migrates old data. A payload that cannot form a valid record (for example
    a non-dict) is still archived the legacy way - the new protocol simply
    refuses to store an invalid record.
    """
    if not isinstance(project, dict):
        return

    resolved = language or i18n.DEFAULT_LANGUAGE

    # --- 1. unified protocol (public API, additive) ------------------
    record = make_localized_record(
        section,
        record_id,
        resolved,
        payload,
        source=SOURCE_AI_GENERATED,
    )

    if record is not None:
        localized_content_put(project, record, copy_on_write=False)

    # --- 2. legacy archive (unchanged behaviour) ---------------------
    archive = project.get(AI_TEXT_ARCHIVE_KEY)

    if not isinstance(archive, dict):
        archive = {}
        project[AI_TEXT_ARCHIVE_KEY] = archive

    bucket = archive.get(resolved)

    if not isinstance(bucket, dict):
        bucket = {}
        archive[resolved] = bucket

    if record_id is None:
        bucket[section] = payload
        return

    records = bucket.get(section)

    if not isinstance(records, dict):
        records = {}
        bucket[section] = records

    records[str(record_id)] = payload


def baseline_ai_text(result) -> dict:
    """
    Extract only the regenerable text fields from a baseline assessment.

    Scores, levels, hazard classifications and environment descriptors are
    deliberately excluded: regenerating text must never change the risk data
    that the score formulas read.
    """
    if not isinstance(result, dict):
        return {}

    payload = {}

    for field in ("risk_chains", "impacts", "actions"):
        values = result.get(field)

        if isinstance(values, list):
            payload[field] = [str(item) for item in values]

    return payload


# ------------------------------------------------------------
# CURRENT-LANGUAGE CONTENT SELECTION
# ------------------------------------------------------------

def _text_list(values) -> List[str]:
    """Keep the stored strings as they are (never re-written or reordered)."""
    if not isinstance(values, list):
        return []

    return [
        str(item)
        for item in values
        if item is not None and str(item).strip()
    ]


def _keep_known(values, is_known):
    """Split a list into (known, unknown_count) without touching the data."""
    known = [value for value in values if is_known(value)]
    return known, len(values) - len(known)


def _result(
    source,
    risk_chains,
    impacts,
    actions,
    needs_generation,
    saved_language,
) -> dict:
    return {
        "source": source,
        "risk_chains": list(risk_chains),
        "impacts": list(impacts),
        "actions": list(actions),
        "needs_generation": bool(needs_generation),
        "saved_language": saved_language,
    }


def get_baseline_display_text(project, language) -> dict:
    """
    Return the baseline text that the current language may safely display.

    Pure: it never mutates ``project``, never calls ``persist()``, never
    touches ``st.session_state``, never reads ``ui_lang`` and never calls the
    AI. The page layer shows the notice / regeneration button based on
    ``needs_generation``.

    ``source`` is one of:

    * ``localized_archive``         current-language AI archive (verbatim)
    * ``deterministic_legacy``      legacy text translated by the display layer
    * ``legacy_current_language``   legacy text already in this language
    * ``missing_current_language``  another language's unknown text (hidden)
    * ``empty``                     no baseline text at all
    """
    current = language or i18n.DEFAULT_LANGUAGE
    project = project if isinstance(project, dict) else {}

    baseline = project.get("baseline_risk")
    baseline = baseline if isinstance(baseline, dict) else {}

    # --- A. current-language archive wins, and is used alone ---------
    payload = ai_text_lookup(project, BASELINE_SECTION, None, current)

    if isinstance(payload, dict):
        chains = _text_list(payload.get("risk_chains"))
        impacts = _text_list(payload.get("impacts"))
        actions = _text_list(payload.get("actions"))

        if chains or impacts or actions:
            return _result(
                SOURCE_LOCALIZED_ARCHIVE,
                chains,
                impacts,
                actions,
                needs_generation=False,
                saved_language=current,
            )

    # --- legacy text (stored directly on baseline_risk) --------------
    legacy_chains = _text_list(baseline.get("risk_chains"))
    legacy_impacts = _text_list(baseline.get("impacts"))
    legacy_actions = _text_list(baseline.get("actions"))
    saved_language = estimated_text_language(baseline)

    if not (legacy_chains or legacy_impacts or legacy_actions):
        # --- D. nothing at all --------------------------------------
        return _result(
            SOURCE_EMPTY,
            [],
            [],
            [],
            needs_generation=saved_language != current,
            saved_language=saved_language,
        )

    if saved_language == current:
        # Legacy text already matches the interface language.
        return _result(
            SOURCE_LEGACY_CURRENT_LANGUAGE,
            legacy_chains,
            legacy_impacts,
            legacy_actions,
            needs_generation=False,
            saved_language=saved_language,
        )

    # --- B / C. legacy text in another language ---------------------
    chains, unknown_chains = _keep_known(legacy_chains, is_chain_known)
    impacts, unknown_impacts = _keep_known(legacy_impacts, is_impact_known)
    actions, unknown_actions = _keep_known(legacy_actions, is_action_known)

    unknown = unknown_chains + unknown_impacts + unknown_actions

    if unknown == 0:
        # Every sentence is a known template -> safe to translate locally.
        return _result(
            SOURCE_DETERMINISTIC_LEGACY,
            chains,
            impacts,
            actions,
            needs_generation=False,
            saved_language=saved_language,
        )

    # Unknown free text exists: hide it and ask for a generated version
    # instead of showing the other language.
    return _result(
        SOURCE_MISSING_CURRENT_LANGUAGE,
        chains,
        impacts,
        actions,
        needs_generation=True,
        saved_language=saved_language,
    )
